test_task:
  matrix:
    - name: Rust Latest
      container:
        image: rust:latest
    - name: Rust 1.65
      container:
        image: rust:1.65-bullseye
    - name: Rust 1.62
      container:
        image: rust:1.62-bullseye
    - name: Rust 1.48
      container:
        image: rust:1.48-bullseye

  registry_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  target_cache:
    folder: target
    fingerprint_script:
      - rustc --version
      - cat Cargo.lock
  setup_script:
    - apt-get update
    - apt-get -y install llvm clang libelf-dev libpcap-dev
    - rustup component add rustfmt
    - rustup component add clippy
  build_script: cargo build --verbose
  test_script: cargo test --verbose
  check_script:
    - cargo fmt --check
    - cargo clippy -- -D warnings
  before_cache_script: rm -rf $CARGO_HOME/registry/index
