[package]
name = "packet-tracer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bimap = "0.6"
btf-rs = {git = "https://github.com/net-trace/btf-rs"}
libbpf-rs = "0.18"
libbpf-sys = "0.8"
log = "0.4"
once_cell = "1.15"
plain = "0.2"

[build-dependencies]
libbpf-cargo = "0.12"
memmap2 = "0.5"
