[package]
name = "packet-tracer"
version = "0.1.0"
edition = "2021"

[features]
test_cap_bpf = []

[dependencies]
anyhow = "1.0"
bimap = "0.6"
clap = { version = "4.0.17", features = ["derive", "string"] }
libbpf-rs = "0.19"
log = "0.4"
once_cell = "1.15"
serde = { version = "1.0.145", features = ["derive"] }
toml = "0.5.9"

[build-dependencies]
libbpf-cargo = "0.13"
