site_name: Retis
site_description: Documentation for Retis, the Linux packet tracing tool
site_author: The Retis community
site_url: https://retis-org.github.io/retis
docs_dir: docs/
repo_name: GitHub
repo_url: https://retis-org.github.com/retis

nav:
  - Overview: README.md
  - Installation: install.md
  - Requirements: requirements.md
  - Contributing: CONTRIBUTING.md
  - Modules:
      - OVS: modules/ovs.md

theme: readthedocs
plugins:
  - search
