name: Build and push container image

on:
  workflow_dispatch:
    inputs:
      release_tags:
        required: false
        default: "next"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment
        run: |
          if [ -z "${{ github.event.inputs.release_tags }}" ]; then
              exit 1
          fi
          echo "RELEASE_TAGS=${{ github.event.inputs.release_tags }}" >> $GITHUB_ENV

      - name: Build container image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: ./Containerfile
          image: retis
          tags: ${{ env.RELEASE_TAGS }}

      - name: Push container image
        id: push_image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: quay.io/retis
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Summary
        run: |
          echo "${{ toJSON(steps.push_image.outputs) }}"
